name: Compile LaTeX and Publish

on:
  push:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload PDF to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Latest Compilation"
          files: src/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}